module.exports = (sequelize, DataTypes) => {
    const CorridaCavalo = sequelize.define('CorridaCavalo', {
        idSportinglife: DataTypes.INTEGER,
        data: DataTypes.DATE,
        hora: DataTypes.STRING,
        name: DataTypes.STRING,
        local: DataTypes.STRING,
        pista: DataTypes.STRING,
        idade: DataTypes.STRING,
        qtdCorredores: DataTypes.INTEGER,
        precisao: DataTypes.STRING,
        oddP1: DataTypes.FLOAT,
        oddP2: DataTypes.FLOAT,
        oddP3: DataTypes.FLOAT,
        oddP4: DataTypes.FLOAT,
        oddP5: DataTypes.FLOAT,
        oddP6: DataTypes.FLOAT,
        oddP7: DataTypes.FLOAT,
        oddP8: DataTypes.FLOAT,
        oddP9: DataTypes.FLOAT,
        oddP10: DataTypes.FLOAT,
        oddP11: DataTypes.FLOAT,
        oddP12: DataTypes.FLOAT,
        oddP1Dec: DataTypes.STRING,
        oddP2Dec: DataTypes.STRING,
        oddP3Dec: DataTypes.STRING,
        oddP4Dec: DataTypes.STRING,
        oddP5Dec: DataTypes.STRING,
        oddP6Dec: DataTypes.STRING,
        oddP7Dec: DataTypes.STRING,
        oddP8Dec: DataTypes.STRING,
        oddP9Dec: DataTypes.STRING,
        oddP10Dec: DataTypes.STRING,
        oddP11Dec: DataTypes.STRING,
        oddP12Dec: DataTypes.STRING,
        premioP1: DataTypes.STRING,
        premioP2: DataTypes.STRING,
        premioP3: DataTypes.STRING,
        premioP4: DataTypes.STRING,
        premioP5: DataTypes.STRING,
        premioP6: DataTypes.STRING,
        premioP7: DataTypes.STRING,
        premioP8: DataTypes.STRING,
        premioP9: DataTypes.STRING,
        premioP10: DataTypes.STRING,
    });

    return CorridaCavalo;
}